language: python
sudo: false
cache:
  pip: true
python:
- 2.7
services:
- docker
install:
- pip install -U tox-travis codecov
script:
- travis_wait 20 bash test-container.sh
after_success:
- codecov --disable search
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: leukgen
  password:
    secure: Q+nkWPUAqx322QGpdV6zVdOqK62OXlNpOBrbu14Wo9JNLcZZYk5ktwxnlbuGima+1bTsPIhhL1HGRneiX3xW3iJScjx393mjtkSFUdWOrBm2dPC4b425hL5AyXqtCvsOGjEzoDuR8eUdnCL0oNH4DyLb/QR3ggG6v4irphiVNxVfdNs1TxN2pA0UuE5qOhgnTYvltghEZuP/6qeGDh7uVjOygUDIEDvzIE5XwSw0Ce8Xpp6gJEto6Oo50NoXjngTMj3JHN3jvetohrcUcIJ35LGSSK02RYUiDye3kkYjIsGhIms/7tC3v6mN3rePeUj44tUdtChgJQdt/lka4vhq34mKPxMnBQj89YF6yCk7SVeKIm96WXmYAM8FcHovmTRQ38jFWSfpaAfCrMY8JGlQf9XtUNIAtPN99Np1SG2JPdD7tZZ2eOdr+1WFHuhrctcHG30Tp2TGfGt9CIUbrdw939DihnAnOfqp5SK4oeWF8SGmIlpR0z4/d2FzPVY37uXEQ5vGkTIZKBmdODR6FEWDv8Bn2nZ5cuePhrwMpPyi1CsKGXA1C4Oof1Me4CzuKcdsEpS2gWAujRNrzZ+N6FRrxXph+TJhMzoSTUi7pLzOQ5A2Ryl91wVqIKSOhuWuPqB50e8ghsZ1EzcY9bdHwWlBUDy1MuQ6onYSHWfXQNJcNLU=
  on:
    tags: true
    repo: leukgen/click_mergevcfs
    python: 2.7
    branch: master
