language: python
sudo: false
cache:
  pip: true
python:
- 2.7
services:
- docker
install:
- pip install -U tox-travis codecov
script:
- travis_wait 20 bash test-container.sh
after_success:
- codecov --disable search
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: leukgen
  password:
    secure: vdxgCzNQBu1nVe0p6Acm3s0oWoo71ifRJYNUw8SeHVthUPjN/WgvpmYHKlUJySvDNQhLWKV9QogSwB/Hx1mWozj2r5Qs2IANc9LBV2oKckGxw5BvdFVrjtheyRlCf4pLebmW1jOIZrrQurlelfAvN+orLWgcy6W/ZP82X+DfLcvO5DCUiqcIaruAnbx+FudF7jUwJ0HIq4jmy0zu0dO0VHPJKgWRFFeQ89uH4KvsbT/ZyK+3C2R6ZTy4XxHbmalp2ZPtYQWXq6w9QvNEBzKIuDdSvR+hEcZsxZm63Fpad49Zfkr6nLf+diBf9KNKUxcc1cIlLjBnR8AIlevAxv7MoNRrlc0ZUj4X9gJEntYGt9gLYK1lB0hQro1+ukO5jVayg3R1GxPYTy0wtIoQjqQlXyrktiQQPdhF12o+oNreZBTTGtrUvfJCT024jOmC7ZopkYy36ILIah+cFL8/4hLIoFP0Ig3bPmJYADPPzgfL+DzJS8W7hFCOmO5MtWE3tsy0jnpFQE+85KbitbkSsk3FNJ5Wftds1V73/wPtavjq87rd5LsPzJbBmMLY8NwRdn15+jlqy1U/+3OXGIVzODwCljE+njiM+eIgGtBsBj+b8ZAOOkM39Jh5NMb7HqeGGOYHz7JGZlQ1uLYc6tYlpNhByqWqi09CAhUBPSQFC2/MCHY=
  on:
    tags: true
    repo: leukgen/click_mergevcfs
    python: 2.7
    branch: master
