language: python

sudo: false

cache:
  pip: true

python:
  - 3.6

services:
  - docker

install:
  - pip install -U tox-travis codecov

script: tox

after_success:
  - codecov --disable search

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: leukgen
  password: <REPLACE THIS AND RUN `travis encrypt --add deploy.password`>
  on:
    tags: true
    repo: leukgen/click_mergevcfs
    python: 3.6
    branch: master
